CREATE DATABASE order_db;
CREATE DATABASE inventory_db;
CREATE DATABASE payment_db;
CREATE DATABASE catalog_db;
CREATE DATABASE audit_db;
CREATE DATABASE digest_db;
CREATE DATABASE keycloak_db;

GRANT ALL PRIVILEGES ON DATABASE order_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE inventory_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE catalog_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE audit_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE digest_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO postgres;
