server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/inventory/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-ws
          uri: ${NOTIFICATION_WS_URL:ws://localhost:8085}
          predicates:
            - Path=/ws-eventix/**

        - id: notification-http
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/notifications/**

        - id: audit-service
          uri: ${AUDIT_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/audit-logs/**

        - id: digest-service
          uri: ${DIGEST_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/v1/digest/**

        - id: keycloak-auth
          uri: ${KEYCLOAK_URL:http://localhost:8089}
          predicates:
            - Path=/realms/**, /resources/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
